#!/system/bin/sh



until [ $(busybox pgrep com.android.systemui) ] ; do
    busybox sleep 1
done

# lowmemorykiller
echo "15104,18176,30464,42752,53248,78336" > /sys/module/lowmemorykiller/parameters/minfree
