#!/system/bin/sh



until [ $(busybox pgrep com.android.systemui) ] ; do
    busybox sleep 1
done

# lowmemorykiller
echo "2816,7936,32256,39168,56832,78336" > /sys/module/lowmemorykiller/parameters/minfree
